"""listing model uupdated

Revision ID: d372d856d3a0
Revises: 203f4fbeccb3
Create Date: 2026-03-09 01:31:15.326745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd372d856d3a0'
down_revision: Union[str, Sequence[str], None] = '203f4fbeccb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Property_Listings_listing_id'), table_name='Property_Listings')
    op.drop_table('Property_Listings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Property_Listings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('location', mysql.TEXT(), nullable=False),
    sa.Column('property_type', mysql.TEXT(), nullable=False),
    sa.Column('bedrooms', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bathrooms', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_guests', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weeks_per_year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.TEXT(), nullable=True),
    sa.Column('original_price', mysql.TEXT(), nullable=True),
    sa.Column('year_built', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Property_Listings_listing_id'), 'Property_Listings', ['listing_id'], unique=True)
    # ### end Alembic commands ###
